# EDA Users

### Imports y lectura de datos

In [40]:
import pandas as pd

In [3]:
usuarios = pd.read_xml("../../EnglishSet/Users.xml")

## Inspección General e Inicial

In [12]:
print("Nº campos:",usuarios.shape[1])
usuarios.head(5)

Nº campos: 12

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId
0,941,613,2010-08-31T22:06:00.843,Dimitris Leventeas,2012-03-05T16:49:50.247,http://students.ceid.upatras.gr/~lebenteas/,"Zurich, Switzerland",<p>Graduate student at ETH.</p>\n,61,2,0,52746.0
1,943,308,2010-08-31T23:37:45.823,Neil McGuigan,2024-01-17T23:24:18.037,https://database-patterns.blogspot.com/,"Vancouver, Canada",<p>I'm a Data Scientist (formerly Data Enginee...,157,40,24,78549.0
2,945,101,2010-09-01T00:27:29.780,Rob Hyndman,2019-01-29T22:12:35.403,http://robjhyndman.com,"Melbourne, Australia","<p><a href=""http://robjhyndman.com"" rel=""nofol...",6,2,0,48509.0
3,946,143,2010-09-01T00:50:28.620,zendar,2018-09-28T08:04:50.277,None,None,NaN,311,5,0,12936.0
4,947,100,2010-09-01T00:57:54.810,Wooble,2023-08-12T02:28:15.810,http://www.geoffreyspear.com,"Pittsburgh, PA",None,10,28,1,38549.0

No aparecen todos los campos, faltan 2, la imagen de perfil y el emailHash. Ninguna de las dos nos iba a ser de utilidad, no pasa nada que no estén. De igual forma, el ID y AccountID no nos sirven de nada ya que son identificadores que no son útiles.

In [14]:
usuarios.dtypes

Id                  int64
Reputation          int64
CreationDate       object
DisplayName        object
LastAccessDate     object
WebsiteUrl         object
Location           object
AboutMe            object
Views               int64
UpVotes             int64
DownVotes           int64
AccountId         float64
dtype: object

Hay que cambiar tipo de las fechas y tal vez sea buena idea ver el comportamiento de Location y tal vez separarlo en ciudad y pais. También parece no comportarse siempre de la misma manera en el AboutMe (aparece un NaN y un None). Esto puede ser casualidad y que la descripción de esa persona en concreto sea NaN.

## Nulls NaNs Nones

In [15]:
usuarios.isna().sum()

Id                     0
Reputation             0
CreationDate           0
DisplayName           31
LastAccessDate         0
WebsiteUrl        345549
Location          296741
AboutMe           312948
Views                  0
UpVotes                0
DownVotes              0
AccountId             17
dtype: int64

Existen unos cuantos nulos en DisplayName, lo que no tiene mucho sentido, esto debe ser o un error de lectura o que tal vez los usuarios hayan desaparecido por x razón. De igual forma hay un comportamiento extraño en los AccountId que tampoco deberían de ser nulos si son identificadores generados automáticamente.

### AccountId NaN

In [ ]:
usuariosNaNAccountId = usuarios[usuarios.isna()["AccountId"]]
usuariosNaNAccountId

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId
120875,217714,1,2017-01-30T18:28:09.177,SIAJSAJ IJSAIJSAJA,2017-01-30T18:28:09.177,None,None,None,0,0,0,NaN
138710,249255,1,2017-07-24T16:52:56.593,Daniel Sasson,2017-07-24T16:52:56.593,None,None,None,1,0,0,NaN
138711,249256,1,2017-07-24T16:53:30.560,a25bedc5-3d09-41b8-82fb-ea6c353d75ae,2017-07-24T16:53:30.560,None,None,None,0,0,0,NaN
139924,220439,1,2017-02-15T06:58:35.247,a25bedc5-3d09-41b8-82fb-ea6c353d75ae,2017-02-15T06:58:35.247,None,None,None,0,0,0,NaN
161556,207143,1,2016-11-22T21:55:29.257,TehCupcakes,2016-11-22T21:55:29.257,None,None,None,0,0,0,NaN
161634,255416,1,2017-09-04T04:22:16.387,Ali Brauda,2017-09-04T04:22:16.387,None,None,None,1,0,0,NaN
176270,292687,1,2018-04-10T22:26:32.647,Gaurov bansal,2018-04-10T22:26:32.647,None,None,None,0,0,0,NaN
192772,269555,1,2017-12-01T06:07:11.260,Richard Morse,2017-12-01T06:07:11.260,None,None,None,2,0,0,NaN
228533,355947,1,2019-07-27T23:37:12.837,Abdallah Ghareeb,2019-07-27T23:37:12.837,None,None,None,1,0,0,NaN
262322,321198,1,2018-10-22T14:01:40.140,a25bedc5-3d09-41b8-82fb-ea6c353d75ae,2018-10-22T14:01:40.140,None,None,None,0,0,0,NaN
268226,361807,1,2019-09-16T14:29:49.470,a25bedc5-3d09-41b8-82fb-ea6c353d75ae,2019-09-16T14:29:49.470,None,None,None,0,0,0,NaN
289215,324390,1,2018-11-15T13:26:30.023,Ahsan Sial,2018-11-15T13:26:30.023,None,None,None,0,0,0,NaN
314394,444083,1,2022-01-12T17:16:45.620,a25bedc5-3d09-41b8-82fb-ea6c353d75ae,2022-01-12T17:16:45.620,None,None,None,0,0,0,NaN
341101,449428,1,2022-03-23T05:31:36.483,a25bedc5-3d09-41b8-82fb-ea6c353d75ae,2022-03-23T05:31:36.483,None,None,None,0,0,0,NaN
341824,447148,1,2022-02-20T10:49:33.670,a25bedc5-3d09-41b8-82fb-ea6c353d75ae,2022-02-20T10:49:33.670,None,None,None,1,0,0,NaN
366586,455395,1,2022-06-16T17:36:44.023,R Berger,2022-06-16T17:36:44.023,None,None,None,0,0,0,NaN
370661,473820,1,2023-02-17T14:53:21.777,English learner,2023-02-17T14:53:21.777,None,None,None,0,0,0,NaN

Todos parecen tener un comportamiento muy similar en los casos de que AccountId sea NaN, muchos comparten el mismo DisplayName "a25bedc5-3d09-41b8-82fb-ea6c353d75ae", todos tienen la misma reputación, no tienen ningún campo en WebsiteUrl, Location, AboutMe, ambos campos de votos...

Pero lo que más curioso parece ser es que las fechas de creación y los últimos accesos coinciden aparentemente así a primera vista.

In [ ]:
(usuariosNaNAccountId["CreationDate"] == usuariosNaNAccountId["LastAccessDate"]).sum()

np.int64(17)

Efectivamente, estas fechas coinciden para los 17 usuarios. Tal vez esto sea porque son cuentas que se empezaron a crear pero nunca terminaron de verificarse o algún tipo de error raro en el sistema. Sin embargo, es raro que algunas de estas cuentas tengan Views.

### DisplayName None

In [30]:
usuariosDisplayName = usuarios[usuarios.isna()["DisplayName"]]
usuariosDisplayName.head(10)

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId
8396,12918,4216,2011-09-12T15:41:09.650,NaN,2024-03-29T17:43:17.280,None,World,None,2000,683,24,558516.0
18343,21658,101,2012-05-28T09:52:25.053,NaN,2017-09-18T23:44:47.167,http://www.stats.stackexchange.com,India,<p>I am a professional with interests in data ...,2,0,0,1521894.0
21132,24693,101,2012-08-09T15:11:07.640,NaN,2021-10-06T13:48:02.590,https://inkrement.ai,"Vienna, Austria",<p>Postdoctoral researcher at the WU Vienna wi...,0,1,0,301763.0
30064,48285,103,2013-07-23T00:01:45.717,NaN,2021-04-12T13:06:13.253,https://www.reddit.com/r/webdev/comments/7szv7...,Undefined,"<p>Developer since 1997, inspired by the possi...",24,5,0,1061383.0
46420,75348,185,2014-05-16T04:36:22.380,NaN,2023-05-12T05:12:41.443,None,None,None,9,5,0,4468448.0
48272,78376,101,2014-06-05T11:13:31.337,NaN,2023-02-06T00:49:13.957,http://mothteeth.com,New Zealand,"<p>I am a game developer from New Zealand, wor...",10,2,0,122868.0
50756,82824,41,2014-07-02T19:17:36.303,NaN,2024-03-28T19:38:57.287,None,"North Carolina, United States",None,12,2,0,297073.0
52652,85010,125,2014-07-14T13:02:04.260,NaN,2024-02-16T17:49:06.457,None,None,None,6,7,0,449292.0
65966,97692,123,2014-11-14T02:11:00.830,NaN,2022-05-09T14:24:56.563,NaN,NaN,<p>NULL</p>\n,4,0,0,2190388.0
70855,166342,1,2016-03-20T16:03:01.593,NaN,2017-03-01T15:34:59.880,http://nan.im/,"Beijing, China",None,0,0,0,960696.0

No parece haber patrones, pero sí que se ve algo que ya se mencionó anteriormente, los NaN como None. Como primer acercamiento vamos a ve al usuario con Id == 97692 para ver si toma como nulos los NaN. Dependiendo de lo que aparezca veremos si también hay que hacer algo con eso o no.

### NaN == Null ???

In [39]:
print(usuariosDisplayName[usuariosDisplayName["Id"] == 97692].isna().sum())
usuariosDisplayName[usuariosDisplayName["Id"] == 97692]

Id                0
Reputation        0
CreationDate      0
DisplayName       1
LastAccessDate    0
WebsiteUrl        1
Location          1
AboutMe           0
Views             0
UpVotes           0
DownVotes         0
AccountId         0
dtype: int64

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId
65966,97692,123,2014-11-14T02:11:00.830,NaN,2022-05-09T14:24:56.563,NaN,NaN,<p>NULL</p>\n,4,0,0,2190388.0

Efectivamente parece tomarlos como nulos. Lo vemos tanto en el campo de WebsiteUrl como en el campo Location. De todas formas, mantendremos un formato similar para todos los datos y los cambiaremos todos a None, que es el formato estándar que suele usar python.